### PR TITLE
rename endpoints

### PR DESCRIPTION
**Pull request by matzapatasphereone**
based on https://github.com/SphereGlobal/server/pull/748

### CODE REVIEW

**Review by DiegoCerdaC — APPROVED** [review]
Looks good to me !

**Review by santiagosphereone — APPROVED** [review]

**Comment by anthony-so** [comment]
will this break merchant integration ?

If so, I'm thinking we might have to forward those 3 calls internally and send out email to communicate with them and give them 1 to 2 months to update to the latest SDK version.

then we create another ticket to clean up

**Comment by matzapatasphereone** [comment]
> will this break merchant integration ?
> 
> If so, I'm thinking we might have to forward those 3 calls internally and send out email to communicate with them and give them 1 to 2 months to update to the latest SDK version.
> 
> then we create another ticket to clean up

@anthony-so cool! Pushed changes in the server to duplicate those endpoints, that way we can consume them like this but hold on in the outside. I think that should work but lemme know if you think otherwise. Thanks!

**Comment by anthony-so** [comment]
LGTM

**Pull request closed without merging**
